from site_cons.site_init import link_wtk_graph


FIGURES = ['sim-hist']

# Get the passed in environment.
Import('env')

# TODO, autogen hist.hist and hist.note from hist.dat

wtk_graph = link_wtk_graph(env)

for fig in FIGURES:
    asyfile = '%s.asy' % fig  # static .asy file
    pyfig = fig.replace('-', '_')
    data = '%s_data' % (pyfig)
    asydata = []
    if data in globals():     # generated data dependencies
        asydata = globals()[data]
    env.Asymptote([asyfile, wtk_graph] + asydata)

# Pass back the modified environment.
Return('env')
